<div class="vc_row wpb_row vc_row-fluid">
    <div class="wpb_column vc_column_container vc_col-sm-12">
        <div class="vc_column-inner ">
            <div class="wpb_wrapper">
                <!-- Nextend Smart Slider 3 #11 - BEGIN -->
                <div id="n2-ss-11-align" class="n2-ss-align n2-ss-slider-align-visible" style="margin-left: -63.5px; width: 1277px;">
                    <div class="n2-padding">
                        <div id="n2-ss-11" class="n2-ss-slider n2-ow n2-ss-load-fade n2-ss-desktop n2-ss-loaded" data-minfontsizedesktopportrait="1" data-minfontsizedesktoplandscape="1" data-minfontsizetabletportrait="1" data-minfontsizetabletlandscape="1" data-minfontsizemobileportrait="1" data-minfontsizemobilelandscape="1" style="font-size: 11.744px; width: 1277px; margin: 0px; height: 415px;" data-fontsize="16">
                            <div class="n2-ss-slider-1 n2-ow n2-grab" style="width: 1277px; padding: 0px; border-width: 0px; height: 415px;">
                                <div class="n2-ss-slider-2 n2-ow">
                                    <div class="n2-ss-slider-3 n2-ow" style="">

                                        <div data-slide-duration="0" data-id="37" class="n2-ss-slide n2-ss-canvas n2-ow  n2-ss-slide-37" style="width: 1277px; height: 415px; left: -100000px;">
                                            <div data-hash="cb016a8b4c8a7aef1b09b29b3d18c918" data-desktop="{{ URL::to('frontEnd/uploads/2018/07/1.png')}}" style="" class="n2-ss-slide-background n2-ow" data-opacity="1" data-blur="0" data-mode="fill" data-x="50" data-y="50"><img title="" src="{{ URL::to('frontEnd/uploads/2018/07/1.png')}}" alt="" style="display: none;">
                                                <div class="n2-ss-background-image n2noselftransition" style="opacity: 1; background-position: 50% 50%; background-image: url(&quot;{{ URL::to('frontEnd/uploads/2018/07/1.png')}}&quot;); overflow: hidden; transform-style: flat; backface-visibility: hidden; transform-origin: 50% 50% 0px; transform: matrix(1.3, 0, 0, 1.3, 0, 0); transition: all 10s ease 0s;"></div>
                                            </div>
                                            <div class="n2-ss-layers-container n2-ow" data-csstextalign="center" style="width: 881px; height: 415px; margin-top: 0px; margin-left: 198px;">
                                                <div class="n2-ss-section-outer" style="">
                                                    <div class="n2-ss-layer n2-ow" style="font-size: 16px;" data-csstextalign="inherit" data-desktopportraitmaxwidth="0" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-pm="content" data-desktopportraitpadding="10|*|10|*|10|*|10|*|px+" data-desktopportraitinneralign="inherit" data-type="content" data-rotation="0" data-desktopportrait="1" data-desktoplandscape="1" data-tabletportrait="1" data-tabletlandscape="1" data-mobileportrait="1" data-mobilelandscape="1" data-adaptivefont="1" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                        <div class="n2-ss-section-main-content n2-ss-layer-content n2-ow" style="padding:0.625em 0.625em 0.625em 0.625em ;" data-verticalalign="center">
                                                            <div class="n2-ss-layer n2-ow" style="margin: 0em; overflow: visible; display: none;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="0" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IkxlZnQgZmFkZSIsIm9wYWNpdHkiOjAsIngiOjQwMH1dfQ==" data-desktopportrait="0" data-desktoplandscape="1" data-tabletportrait="0" data-tabletlandscape="1" data-mobileportrait="1" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div id="n2-ss-11item1" class="n2-font-38cd25c499ec1da6f7bd788d93f3c8df-hover n2-style-5db3eb698375544404f3cdafad9da567-heading   n2-ow" style="display:block;">HỆ THỐNG PHÒNG GAME<br>SỐ 1 VIỆT NAM</div>
                                                            </div>
                                                            <div class="n2-ss-layer n2-ow n2-ss-has-maxwidth  container float-left-slide" style="margin: 0em; max-width: 1180px; overflow: visible; font-size: 100%; opacity: 1; transform: matrix(1, 0, 0, 1, 0, 0); transform-origin: 50% 50% 0px;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="1180" data-cssselfalign="left" data-desktopportraitselfalign="left" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IkxlZnQgZmFkZSIsIm9wYWNpdHkiOjAsIngiOjQwMH1dfQ==" data-desktopportrait="1" data-desktoplandscape="1" data-tabletportrait="1" data-tabletlandscape="1" data-mobileportrait="0" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div class="n2-style-988cd5fcc253042be95be1a9c67916a2-heading  n2-ss-img-wrapper n2-ow" style="overflow:hidden;"><img src="{{ URL::to('frontEnd/uploads/2018/07/slide-1-big.png')}}" id="n2-ss-11item2" alt="Image is not available" style="display: inline-block; max-width: 100%; width: auto;height: auto;" class=" n2-ow" title=""></div>
                                                            </div>
                                                            <div class="n2-ss-layer n2-ow" style="margin: 0em; overflow: visible; display: none;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="0" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IkxlZnQgZmFkZSIsImRlbGF5IjowLjUsIm9wYWNpdHkiOjAsIngiOjQwMH1dfQ==" data-desktopportrait="0" data-desktoplandscape="1" data-tabletportrait="0" data-tabletlandscape="1" data-mobileportrait="1" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div class="n2-ow n2-ow-all n2-ss-desktop n2-ss-mobile n2-ss-tablet">
                                                                    <p class="n2-font-ef00fb91ee234f15b8037cb581776ed5-paragraph  n2-style-534e9b4d532093b74f0acd993e3488e5-heading  n2-ow"><b>DẪN ĐẦU CÔNG NGHỆ, HOÀN HẢO VỀ DỊCH VỤ</b></p>
                                                                </div>
                                                            </div>
                                                            <div class="n2-ss-layer n2-ow n2-ss-has-maxwidth  popmake-1900  hover-white pum-trigger" style="margin: 0em; max-width: 600px; overflow: visible; display: none; cursor: pointer;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="600" data-cssselfalign="left" data-desktopportraitselfalign="left" data-mobileportraitselfalign="center" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IkxlZnQiLCJkZWxheSI6MSwieCI6NDAwfV19" data-desktopportrait="0" data-desktoplandscape="1" data-tabletportrait="0" data-tabletlandscape="1" data-mobileportrait="1" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div class="nextend-smartslider-button-container n2-ow n2-font-4669165dee3c2406bfe110cc3c6709a8-link " style="cursor: pointer; display:inline-block;white-space:nowrap;"><a style="display:inline-block;" class="n2-style-0c4c15047218596e2dfdd2403e17f29a-heading  n2-ow " onclick="return false;" href="#">ĐĂNG KÝ TƯ VẤN PHÒNG GAME</a></div>
                                                            </div>
                                                            <div class="n2-ss-layer n2-ow n2-ss-has-maxwidth  container float-left-slide" style="margin: 0em; max-width: 1180px; overflow: visible; font-size: 100%; opacity: 1; transform: matrix(1, 0, 0, 1, 0, 0); transform-origin: 50% 50% 0px;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="1180" data-cssselfalign="left" data-desktopportraitselfalign="left" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IkxlZnQgZmFkZSIsImRlbGF5IjowLjUsIm9wYWNpdHkiOjAsIngiOjQwMH1dfQ==" data-desktopportrait="1" data-desktoplandscape="1" data-tabletportrait="1" data-tabletlandscape="1" data-mobileportrait="0" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div class="n2-style-988cd5fcc253042be95be1a9c67916a2-heading  n2-ss-img-wrapper n2-ow" style="overflow:hidden;"><img src="{{ URL::to('frontEnd/uploads/2018/07/slide-1-small.png')}}" id="n2-ss-11item5"    alt="Image is not available" style="display: inline-block; max-width: 100%; width: auto;height: auto;" class=" n2-ow" title=""></div>
                                                            </div>
                                                            <div class="n2-ss-layer n2-ow n2-ss-has-maxwidth  popmake-1900 container float-left-slide hover-white pum-trigger" style="margin: 0em; max-width: 1180px; overflow: visible; font-size: 100%; opacity: 1; transform: matrix(1, 0, 0, 1, 0, 0); transform-origin: 50% 50% 0px; cursor: pointer;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="1180" data-cssselfalign="left" data-desktopportraitselfalign="left" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IkxlZnQgZmFkZSIsImRlbGF5IjoxLCJvcGFjaXR5IjowLCJ4Ijo0MDB9XX0=" data-desktopportrait="1" data-desktoplandscape="1" data-tabletportrait="1" data-tabletlandscape="1" data-mobileportrait="0" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div class=" n2-ss-img-wrapper n2-ow" style="overflow:hidden;"><img src="https://cybercore.vn/wp-content/uploads/2018/07/btn-dang-ky-phong-game.png" id="n2-ss-11item6" alt="Image is not available" style="display: inline-block; max-width: 100%; width: auto;height: auto;" class=" n2-ow" title=""></div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div data-slide-duration="0" data-id="38" class="n2-ss-slide n2-ss-canvas n2-ow  n2-ss-slide-38" style="width: 1277px; height: 415px; left: -100000px;">
                                            <div data-hash="10cab8fed68a5b50060c21c315f574b6" data-desktop="{{ URL::to('frontEnd/uploads/2018/07/2.png')}}" style="" class="n2-ss-slide-background n2-ow" data-opacity="1" data-blur="0" data-mode="fill" data-x="50" data-y="50"><img title="" src="{{ URL::to('frontEnd/uploads/2018/07/2.png')}}" alt="" style="display: none;">
                                                <div class="n2-ss-background-image n2noselftransition" style="opacity: 1; background-position: 50% 50%; background-image: url(&quot;{{ URL::to('frontEnd/uploads/2018/07/2.png')}}&quot;); overflow: hidden; transform-style: flat; backface-visibility: hidden; transform-origin: 50% 50% 0px; transform: matrix(1.3, 0, 0, 1.3, 0, 0); transition: all 10s ease 0s;"></div>
                                            </div>
                                            <div class="n2-ss-layers-container n2-ow" data-csstextalign="center" style="width: 881px; height: 415px; margin-top: 0px; margin-left: 198px;">
                                                <div class="n2-ss-section-outer" style="">
                                                    <div class="n2-ss-layer n2-ow" style="font-size: 16px;" data-csstextalign="inherit" data-desktopportraitmaxwidth="0" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-pm="content" data-desktopportraitpadding="10|*|10|*|10|*|10|*|px+" data-desktopportraitinneralign="inherit" data-type="content" data-rotation="0" data-desktopportrait="1" data-desktoplandscape="1" data-tabletportrait="1" data-tabletlandscape="1" data-mobileportrait="1" data-mobilelandscape="1" data-adaptivefont="1" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                        <div class="n2-ss-section-main-content n2-ss-layer-content n2-ow" style="padding:0.625em 0.625em 0.625em 0.625em ;" data-verticalalign="center">
                                                            <div class="n2-ss-layer n2-ow" style="margin: 0em; overflow: visible; display: none;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="0" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IlJpZ2h0IGZhZGUiLCJvcGFjaXR5IjowLCJ4IjotNDAwfV19" data-desktopportrait="0" data-desktoplandscape="1" data-tabletportrait="0" data-tabletlandscape="1" data-mobileportrait="1" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div id="n2-ss-11item7" class="n2-font-38cd25c499ec1da6f7bd788d93f3c8df-hover n2-style-5db3eb698375544404f3cdafad9da567-heading   n2-ow" style="display:block;">TẠO RA SỰ KHÁC BIỆT</div>
                                                            </div>
                                                            <div class="n2-ss-layer n2-ow" style="margin: 0em; overflow: visible; display: none;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="0" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IlJpZ2h0IGZhZGUiLCJkZWxheSI6MC41LCJvcGFjaXR5IjowLCJ4IjotNDAwfV19" data-desktopportrait="0" data-desktoplandscape="1" data-tabletportrait="0" data-tabletlandscape="1" data-mobileportrait="1" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div class="n2-ow n2-ow-all n2-ss-desktop n2-ss-mobile n2-ss-tablet">
                                                                    <p class="n2-font-ef00fb91ee234f15b8037cb581776ed5-paragraph  n2-style-534e9b4d532093b74f0acd993e3488e5-heading  n2-ow"><b>BẮT KỊP XU THỂ, SÁNG TẠO KHÔNG NGỪNG NGHỈ</b><br>
                                                                        <b>NHẰM TẠO RA CÁC TUYỆT TÁC MANG ĐẬM CHẤT GAME</b></p>
                                                                </div>
                                                            </div>
                                                            <div class="n2-ss-layer n2-ow n2-ss-has-maxwidth  popmake-1900  hover-white pum-trigger" style="margin: 0em; max-width: 600px; overflow: visible; display: none; cursor: pointer;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="600" data-cssselfalign="right" data-desktopportraitselfalign="right" data-mobileportraitselfalign="center" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IlJpZ2h0IGZhZGUiLCJkZWxheSI6MSwib3BhY2l0eSI6MCwieCI6LTQwMH1dfQ==" data-desktopportrait="0" data-desktoplandscape="1" data-tabletportrait="0" data-tabletlandscape="1" data-mobileportrait="1" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div class="nextend-smartslider-button-container n2-ow n2-font-4669165dee3c2406bfe110cc3c6709a8-link " style="cursor: pointer; display:inline-block;white-space:nowrap;"><a style="display:inline-block;" class="n2-style-0c4c15047218596e2dfdd2403e17f29a-heading  n2-ow " onclick="return false;" href="#">ĐĂNG KÝ TƯ VẤN PHÒNG GAME</a></div>
                                                            </div>
                                                            <div class="n2-ss-layer n2-ow n2-ss-has-maxwidth  container float-right-slide" style="margin: 0em; max-width: 1180px; overflow: visible; font-size: 100%; opacity: 1; transform: matrix(1, 0, 0, 1, 0, 0); transform-origin: 50% 50% 0px;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="1180" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IlJpZ2h0IGZhZGUiLCJvcGFjaXR5IjowLCJ4IjotNDAwfV19" data-desktopportrait="1" data-desktoplandscape="1" data-tabletportrait="1" data-tabletlandscape="1" data-mobileportrait="0" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div class="n2-style-988cd5fcc253042be95be1a9c67916a2-heading  n2-ss-img-wrapper n2-ow" style="overflow:hidden;"><img src="//cybercore.vn/wp-content/uploads/2018/07/slide-2-big.png" id="n2-ss-11item10" alt="Image is not available" style="display: inline-block; max-width: 100%; width: auto;height: auto;" class=" n2-ow" title=""></div>
                                                            </div>
                                                            <div class="n2-ss-layer n2-ow n2-ss-has-maxwidth  container float-right-slide" style="margin: 0em; max-width: 1180px; overflow: visible; font-size: 100%; opacity: 1; transform: matrix(1, 0, 0, 1, 0, 0); transform-origin: 50% 50% 0px;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="1180" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IlJpZ2h0IGZhZGUiLCJkZWxheSI6MC41LCJvcGFjaXR5IjowLCJ4IjotNDAwfV19" data-desktopportrait="1" data-desktoplandscape="1" data-tabletportrait="1" data-tabletlandscape="1" data-mobileportrait="0" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div class="n2-style-988cd5fcc253042be95be1a9c67916a2-heading  n2-ss-img-wrapper n2-ow" style="overflow:hidden;"><img src="//cybercore.vn/wp-content/uploads/2018/07/slide-2-small.png" id="n2-ss-11item11" alt="Image is not available" style="display: inline-block; max-width: 100%; width: auto;height: auto;" class=" n2-ow" title=""></div>
                                                            </div>
                                                            <div class="n2-ss-layer n2-ow n2-ss-has-maxwidth  popmake-1900 container float-right-slide  hover-white pum-trigger" style="margin: 0em; max-width: 1180px; overflow: visible; font-size: 100%; opacity: 1; transform: matrix(1, 0, 0, 1, 0, 0); transform-origin: 50% 50% 0px; cursor: pointer;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="1180" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IlJpZ2h0IGZhZGUiLCJkZWxheSI6MSwib3BhY2l0eSI6MCwieCI6LTQwMH1dfQ==" data-desktopportrait="1" data-desktoplandscape="1" data-tabletportrait="1" data-tabletlandscape="1" data-mobileportrait="0" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div class=" n2-ss-img-wrapper n2-ow" style="overflow:hidden;"><img src="https://cybercore.vn/wp-content/uploads/2018/07/btn-dang-ky-phong-game.png" id="n2-ss-11item12" alt="Image is not available" style="display: inline-block; max-width: 100%; width: auto;height: auto;" class=" n2-ow" title=""></div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div data-slide-duration="0" data-id="39" class="n2-ss-slide n2-ss-canvas n2-ow  n2-ss-slide-39" style="width: 1277px; height: 415px; left: -100000px;">
                                            <div data-hash="ae77c8ac3dccc124f3192f5421646669" data-desktop="//cybercore.vn/wp-content/uploads/2018/07/3.png" style="" class="n2-ss-slide-background n2-ow" data-opacity="1" data-blur="0" data-mode="fill" data-x="50" data-y="50"><img title="" src="//cybercore.vn/wp-content/uploads/2018/07/3.png" alt="" style="display: none;">
                                                <div class="n2-ss-background-image n2noselftransition" style="opacity: 1; background-position: 50% 50%; background-image: url(&quot;//cybercore.vn/wp-content/uploads/2018/07/3.png&quot;); overflow: hidden; transform-style: flat; backface-visibility: hidden; transform-origin: 50% 50% 0px; transform: matrix(1.12, 0, 0, 1.12, 0, 0); transition: all 10s ease 0s;"></div>
                                            </div>
                                            <div class="n2-ss-layers-container n2-ow" data-csstextalign="center" style="width: 881px; height: 415px; margin-top: 0px; margin-left: 198px;">
                                                <div class="n2-ss-section-outer" style="">
                                                    <div class="n2-ss-layer n2-ow" style="font-size: 16px;" data-csstextalign="inherit" data-desktopportraitmaxwidth="0" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-pm="content" data-desktopportraitpadding="10|*|10|*|10|*|10|*|px+" data-desktopportraitinneralign="inherit" data-type="content" data-rotation="0" data-desktopportrait="1" data-desktoplandscape="1" data-tabletportrait="1" data-tabletlandscape="1" data-mobileportrait="1" data-mobilelandscape="1" data-adaptivefont="1" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                        <div class="n2-ss-section-main-content n2-ss-layer-content n2-ow" style="padding:0.625em 0.625em 0.625em 0.625em ;" data-verticalalign="center">
                                                            <div class="n2-ss-layer n2-ow" style="margin: 0em; overflow: visible; display: none;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="0" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IkxlZnQgZmFkZSIsIm9wYWNpdHkiOjAsIngiOjQwMH1dfQ==" data-desktopportrait="0" data-desktoplandscape="1" data-tabletportrait="0" data-tabletlandscape="1" data-mobileportrait="1" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div id="n2-ss-11item13" class="n2-font-38cd25c499ec1da6f7bd788d93f3c8df-hover n2-style-5db3eb698375544404f3cdafad9da567-heading   n2-ow" style="display:block;">CAM KẾT GIÁ TỐT NHẤT</div>
                                                            </div>
                                                            <div class="n2-ss-layer n2-ow" style="margin: 0em; overflow: visible; display: none;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="0" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IkxlZnQgZmFkZSIsImRlbGF5IjowLjUsIm9wYWNpdHkiOjAsIngiOjQwMH1dfQ==" data-desktopportrait="0" data-desktoplandscape="1" data-tabletportrait="0" data-tabletlandscape="1" data-mobileportrait="1" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div class="n2-ow n2-ow-all n2-ss-desktop n2-ss-mobile n2-ss-tablet">
                                                                    <p class="n2-font-ef00fb91ee234f15b8037cb581776ed5-paragraph  n2-style-534e9b4d532093b74f0acd993e3488e5-heading  n2-ow"><b>CUNG CẤP NHỮNG DÒNG SẢN PHẨM CHUYÊN GAME ĐỘC QUYỀN</b><br>
                                                                        <b>VỚI CHI PHÍ CỰC KÌ HỢP LÝ</b></p>
                                                                </div>
                                                            </div>
                                                            <div class="n2-ss-layer n2-ow n2-ss-has-maxwidth  popmake-1900  hover-white pum-trigger" style="margin: 0em; max-width: 600px; overflow: visible; display: none; cursor: pointer;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="600" data-cssselfalign="left" data-desktopportraitselfalign="left" data-mobileportraitselfalign="center" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IkxlZnQgZmFkZSIsImRlbGF5IjoxLCJvcGFjaXR5IjowLCJ4Ijo0MDB9XX0=" data-desktopportrait="0" data-desktoplandscape="1" data-tabletportrait="0" data-tabletlandscape="1" data-mobileportrait="1" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div class="nextend-smartslider-button-container n2-ow n2-font-4669165dee3c2406bfe110cc3c6709a8-link " style="cursor: pointer; display:inline-block;white-space:nowrap;"><a style="display:inline-block;" class="n2-style-0c4c15047218596e2dfdd2403e17f29a-heading  n2-ow " onclick="return false;" href="#">ĐĂNG KÝ TƯ VẤN PHÒNG GAME</a></div>
                                                            </div>
                                                            <div class="n2-ss-layer n2-ow n2-ss-has-maxwidth  container float-left-slide" style="margin: 0em; max-width: 1180px; overflow: visible; font-size: 100%; opacity: 1; transform: matrix(1, 0, 0, 1, 0, 0); transform-origin: 50% 50% 0px;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="1180" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IkxlZnQgZmFkZSIsIm9wYWNpdHkiOjAsIngiOjQwMH1dfQ==" data-desktopportrait="1" data-desktoplandscape="1" data-tabletportrait="1" data-tabletlandscape="1" data-mobileportrait="0" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div class="n2-style-988cd5fcc253042be95be1a9c67916a2-heading  n2-ss-img-wrapper n2-ow" style="overflow:hidden;"><img src="//cybercore.vn/wp-content/uploads/2018/07/slide-3-big.png" id="n2-ss-11item16" alt="Image is not available" style="display: inline-block; max-width: 100%; width: auto;height: auto;" class=" n2-ow" title=""></div>
                                                            </div>
                                                            <div class="n2-ss-layer n2-ow n2-ss-has-maxwidth  container float-left-slide" style="margin: 0em; max-width: 1180px; overflow: visible; font-size: 100%; opacity: 1; transform: matrix(1, 0, 0, 1, 0, 0); transform-origin: 50% 50% 0px;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="1180" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IkxlZnQgZmFkZSIsImRlbGF5IjowLjUsIm9wYWNpdHkiOjAsIngiOjQwMH1dfQ==" data-desktopportrait="1" data-desktoplandscape="1" data-tabletportrait="1" data-tabletlandscape="1" data-mobileportrait="0" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div class="n2-style-988cd5fcc253042be95be1a9c67916a2-heading  n2-ss-img-wrapper n2-ow" style="overflow:hidden;"><img src="//cybercore.vn/wp-content/uploads/2018/07/slide-3-small.png" id="n2-ss-11item17" alt="Image is not available" style="display: inline-block; max-width: 100%; width: auto;height: auto;" class=" n2-ow" title=""></div>
                                                            </div>
                                                            <div class="n2-ss-layer n2-ow n2-ss-has-maxwidth  popmake-1900 container float-left-slide  hover-white pum-trigger" style="margin: 0em; max-width: 1180px; overflow: visible; font-size: 100%; opacity: 1; transform: matrix(1, 0, 0, 1, 0, 0); transform-origin: 50% 50% 0px; cursor: pointer;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="1180" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IkxlZnQgZmFkZSIsImRlbGF5IjoxLCJvcGFjaXR5IjowLCJ4Ijo0MDB9XX0=" data-desktopportrait="1" data-desktoplandscape="1" data-tabletportrait="1" data-tabletlandscape="1" data-mobileportrait="0" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div class="n2-style-5db3eb698375544404f3cdafad9da567-heading  n2-ss-img-wrapper n2-ow" style="overflow:hidden;"><img src="https://cybercore.vn/wp-content/uploads/2018/07/btn-dang-ky-phong-game.png" id="n2-ss-11item18" alt="Image is not available" style="display: inline-block; max-width: 100%; width: auto;height: auto;" class=" n2-ow" title=""></div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div data-slide-duration="0" data-id="40" class="n2-ss-slide n2-ss-canvas n2-ow  n2-ss-slide-40" style="width: 1277px; height: 415px; z-index: 4; left: -1277px;">
                                            <div data-hash="555ce5043c6bfa8b119f7ae2fbe6d85d" data-desktop="//cybercore.vn/wp-content/uploads/2018/07/4.png" style="" class="n2-ss-slide-background n2-ow" data-opacity="1" data-blur="0" data-mode="fill" data-x="50" data-y="50"><img title="" src="//cybercore.vn/wp-content/uploads/2018/07/4.png" alt="" style="display: none;">
                                                <div class="n2-ss-background-image" style="opacity: 1; background-position: 50% 50%; background-image: url(&quot;//cybercore.vn/wp-content/uploads/2018/07/4.png&quot;); overflow: hidden; transform-style: flat; backface-visibility: hidden; transform-origin: 50% 50% 0px; transform: matrix(1.3, 0, 0, 1.3, 44.04, 0); transition: all 10s ease 0s;"></div>
                                            </div>
                                            <div class="n2-ss-layers-container n2-ow" data-csstextalign="center" style="width: 881px; height: 415px; margin-top: 0px; margin-left: 198px;">
                                                <div class="n2-ss-section-outer" style="">
                                                    <div class="n2-ss-layer n2-ow" style="font-size: 16px;" data-csstextalign="inherit" data-desktopportraitmaxwidth="0" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-pm="content" data-desktopportraitpadding="10|*|10|*|10|*|10|*|px+" data-desktopportraitinneralign="inherit" data-type="content" data-rotation="0" data-desktopportrait="1" data-desktoplandscape="1" data-tabletportrait="1" data-tabletlandscape="1" data-mobileportrait="1" data-mobilelandscape="1" data-adaptivefont="1" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                        <div class="n2-ss-section-main-content n2-ss-layer-content n2-ow" style="padding:0.625em 0.625em 0.625em 0.625em ;" data-verticalalign="center">
                                                            <div class="n2-ss-layer n2-ow n2-ss-has-maxwidth" style="margin: 0em; max-width: 1180px; overflow: visible; font-size: 100%; opacity: 1; transform: matrix(1, 0, 0, 1, 0, 0); transform-origin: 50% 50% 0px;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="1180" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IlVwc2NhbGVkIiwib3BhY2l0eSI6MCwic2NhbGVYIjoyLCJzY2FsZVkiOjJ9XX0=" data-desktopportrait="1" data-desktoplandscape="1" data-tabletportrait="1" data-tabletlandscape="1" data-mobileportrait="0" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div class="n2-style-988cd5fcc253042be95be1a9c67916a2-heading  n2-ss-img-wrapper n2-ow" style="overflow:hidden;"><img src="//cybercore.vn/wp-content/uploads/2018/07/slide-4-big.png" id="n2-ss-11item19" alt="Image is not available" style="display: inline-block; max-width: 100%; width: auto;height: auto;" class=" n2-ow" title=""></div>
                                                            </div>
                                                            <div class="n2-ss-layer n2-ow n2-ss-has-maxwidth" style="margin: 0em; max-width: 1180px; overflow: visible; font-size: 100%; opacity: 1; transform: matrix(1, 0, 0, 1, 0, 0); transform-origin: 50% 50% 0px;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="1180" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IkRvd25zY2FsZWQiLCJkZWxheSI6MC41LCJzY2FsZVgiOjAsInNjYWxlWSI6MH1dfQ==" data-desktopportrait="1" data-desktoplandscape="1" data-tabletportrait="1" data-tabletlandscape="1" data-mobileportrait="0" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div class="n2-style-988cd5fcc253042be95be1a9c67916a2-heading  n2-ss-img-wrapper n2-ow" style="overflow:hidden;"><img src="//cybercore.vn/wp-content/uploads/2018/07/slide-4-small.png" id="n2-ss-11item20" alt="Image is not available" style="display: inline-block; max-width: 100%; width: auto;height: auto;" class=" n2-ow" title=""></div>
                                                            </div>
                                                            <div class="n2-ss-layer n2-ow popmake-1900  hover-white pum-trigger" style="margin: 0em; overflow: visible; font-size: 100%; opacity: 1; transform: matrix(1, 0, 0, 1, 0, 0); transform-origin: 50% 50% 0px; cursor: pointer;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="0" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IkRvd25zY2FsZWQiLCJkZWxheSI6MSwic2NhbGVYIjowLCJzY2FsZVkiOjB9XX0=" data-desktopportrait="1" data-desktoplandscape="1" data-tabletportrait="1" data-tabletlandscape="1" data-mobileportrait="0" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div class="n2-style-5db3eb698375544404f3cdafad9da567-heading  n2-ss-img-wrapper n2-ow" style="overflow:hidden;"><img src="https://cybercore.vn/wp-content/uploads/2018/07/btn-dang-ky-phong-game.png" id="n2-ss-11item21" alt="Image is not available" style="display: inline-block; max-width: 100%; width: auto;height: auto;" class=" n2-ow" title=""></div>
                                                            </div>
                                                            <div class="n2-ss-layer n2-ow" style="margin: 0em; overflow: visible; display: none;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="0" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IkRvd25zY2FsZWQiLCJzY2FsZVgiOjAsInNjYWxlWSI6MH1dfQ==" data-desktopportrait="0" data-desktoplandscape="1" data-tabletportrait="0" data-tabletlandscape="1" data-mobileportrait="1" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div class="n2-ow n2-ow-all n2-ss-desktop n2-ss-mobile n2-ss-tablet">
                                                                    <p class="n2-font-c44d6eec985e21334077c84e156d0c13-paragraph   n2-ow"><b>ĐỘI NGŨ KỸ THUẬT CHUYÊN NGHIỆP</b></p>
                                                                </div>
                                                            </div>
                                                            <div class="n2-ss-layer n2-ow" style="margin: 0em; overflow: visible; display: none;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="0" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IkRvd25zY2FsZWQiLCJkZWxheSI6MC41LCJzY2FsZVgiOjAsInNjYWxlWSI6MH1dfQ==" data-desktopportrait="0" data-desktoplandscape="1" data-tabletportrait="0" data-tabletlandscape="1" data-mobileportrait="1" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div class="n2-ow n2-ow-all n2-ss-desktop n2-ss-mobile n2-ss-tablet">
                                                                    <p class="n2-font-ef00fb91ee234f15b8037cb581776ed5-paragraph   n2-ow">HỖ TRỢ TỪ XA, XỬ LÝ TRỰC TIẾP ĐẢM BẢO QUÁ TRÌNH KINH DOANH KHÔNG BỊ GIÁN ĐOẠN</p>
                                                                </div>
                                                            </div>
                                                            <div class="n2-ss-layer n2-ow popmake-1900  hover-white pum-trigger" style="margin: 0em; overflow: visible; display: none; cursor: pointer;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="0" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IkRvd25zY2FsZWQiLCJkZWxheSI6MSwic2NhbGVYIjowLCJzY2FsZVkiOjB9XX0=" data-desktopportrait="0" data-desktoplandscape="1" data-tabletportrait="0" data-tabletlandscape="1" data-mobileportrait="1" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div class="nextend-smartslider-button-container n2-ow n2-font-e0a01f20f2e838e145824ef9067626d9-link " style="cursor: pointer; display:inline-block;white-space:nowrap;"><a style="display:inline-block;" class="n2-style-0c4c15047218596e2dfdd2403e17f29a-heading  n2-ow " onclick="return false;" href="#">ĐĂNG KÝ TƯ VẤN PHÒNG GAME</a></div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div data-slide-duration="0" data-id="41" class="n2-ss-slide n2-ss-canvas n2-ow  n2-ss-slide-41 n2-ss-slide-active" style="width: 1277px; height: 415px; left: 0px; z-index: 5;">
                                            <div data-hash="da8c2dbf94d90fe629f7a3eade1d12b8" data-desktop="//cybercore.vn/wp-content/uploads/2018/07/5.png" style="" class="n2-ss-slide-background n2-ow" data-opacity="1" data-blur="0" data-mode="fill" data-x="50" data-y="50"><img title="" src="//cybercore.vn/wp-content/uploads/2018/07/5.png" alt="" style="display: none;">
                                                <div class="n2-ss-background-image" style="opacity: 1; background-position: 50% 50%; background-image: url(&quot;//cybercore.vn/wp-content/uploads/2018/07/5.png&quot;); overflow: hidden; transform-style: flat; backface-visibility: hidden; transform-origin: 50% 50% 0px; transform: matrix(1.12, 0, 0, 1.12, 44.04, 0); transition: all 10s ease 0s;"></div>
                                            </div>
                                            <div class="n2-ss-layers-container n2-ow" data-csstextalign="center" style="width: 881px; height: 415px; margin-top: 0px; margin-left: 198px;">
                                                <div class="n2-ss-section-outer" style="">
                                                    <div class="n2-ss-layer n2-ow" style="font-size: 16px;" data-csstextalign="inherit" data-desktopportraitmaxwidth="0" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-pm="content" data-desktopportraitpadding="10|*|10|*|10|*|10|*|px+" data-desktopportraitinneralign="inherit" data-type="content" data-rotation="0" data-desktopportrait="1" data-desktoplandscape="1" data-tabletportrait="1" data-tabletlandscape="1" data-mobileportrait="1" data-mobilelandscape="1" data-adaptivefont="1" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                        <div class="n2-ss-section-main-content n2-ss-layer-content n2-ow" style="padding:0.625em 0.625em 0.625em 0.625em ;" data-verticalalign="center">
                                                            <div class="n2-ss-layer n2-ow" style="margin: 0em; overflow: visible; display: none;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="0" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-mobileportraitselfalign="inherit" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IlJpZ2h0IGZhZGUiLCJvcGFjaXR5IjowLCJ4IjotNDAwfV19" data-desktopportrait="0" data-desktoplandscape="1" data-tabletportrait="0" data-tabletlandscape="1" data-mobileportrait="1" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div id="n2-ss-11item25" class="n2-font-38cd25c499ec1da6f7bd788d93f3c8df-hover n2-style-5db3eb698375544404f3cdafad9da567-heading   n2-ow" style="display:block;">GIẢI PHÁP QUẢN LÝ<br>PHÒNG MÁY TỐI ƯU</div>
                                                            </div>
                                                            <div class="n2-ss-layer n2-ow" style="margin: 0em; overflow: visible; display: none;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="0" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IlJpZ2h0IGZhZGUiLCJkZWxheSI6MC41LCJvcGFjaXR5IjowLCJ4IjotNDAwfV19" data-desktopportrait="0" data-desktoplandscape="1" data-tabletportrait="0" data-tabletlandscape="1" data-mobileportrait="1" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div class="n2-ow n2-ow-all n2-ss-desktop n2-ss-mobile n2-ss-tablet">
                                                                    <p class="n2-font-ef00fb91ee234f15b8037cb581776ed5-paragraph  n2-style-534e9b4d532093b74f0acd993e3488e5-heading  n2-ow"><b>VỚI HƠN 10 NĂM KINH NGHIỆM PHÒNG GAME</b><br>
                                                                        <b>CHÚNG TÔI ĐỒNG HÀNH CÙNG BẠN ĐI ĐẾN THÀNH CÔNG</b></p>
                                                                </div>
                                                            </div>
                                                            <div class="n2-ss-layer n2-ow n2-ss-has-maxwidth  popmake-1900  hover-white pum-trigger" style="margin: 0em; max-width: 600px; overflow: visible; display: none; cursor: pointer;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="600" data-cssselfalign="right" data-desktopportraitselfalign="right" data-mobileportraitselfalign="center" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IlJpZ2h0IGZhZGUiLCJkZWxheSI6MSwib3BhY2l0eSI6MCwieCI6LTQwMH1dfQ==" data-desktopportrait="0" data-desktoplandscape="1" data-tabletportrait="0" data-tabletlandscape="1" data-mobileportrait="1" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div class="nextend-smartslider-button-container n2-ow n2-font-4669165dee3c2406bfe110cc3c6709a8-link " style="cursor: pointer; display:inline-block;white-space:nowrap;"><a style="display:inline-block;" class="n2-style-0c4c15047218596e2dfdd2403e17f29a-heading  n2-ow " onclick="return false;" href="#">ĐĂNG KÝ TƯ VẤN PHÒNG GAME</a></div>
                                                            </div>
                                                            <div class="n2-ss-layer n2-ow n2-ss-has-maxwidth  container float-right-slide" style="margin: 0em; max-width: 1180px; overflow: visible; font-size: 100%; opacity: 0; transform: matrix(1, 0, 0, 1, 293.6, 0); transform-origin: 50% 50% 0px;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="1180" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IlJpZ2h0IGZhZGUiLCJvcGFjaXR5IjowLCJ4IjotNDAwfV19" data-desktopportrait="1" data-desktoplandscape="1" data-tabletportrait="1" data-tabletlandscape="1" data-mobileportrait="0" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div class="n2-style-988cd5fcc253042be95be1a9c67916a2-heading  n2-ss-img-wrapper n2-ow" style="overflow:hidden;"><img src="//cybercore.vn/wp-content/uploads/2018/07/slide-5-big.png" id="n2-ss-11item28" alt="Image is not available" style="display: inline-block; max-width: 100%; width: auto;height: auto;" class=" n2-ow" title=""></div>
                                                            </div>
                                                            <div class="n2-ss-layer n2-ow n2-ss-has-maxwidth  container float-right-slide" style="margin: 0em; max-width: 1180px; overflow: visible; font-size: 100%; opacity: 0; transform: matrix(1, 0, 0, 1, 293.6, 0); transform-origin: 50% 50% 0px;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="1180" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IlJpZ2h0IGZhZGUiLCJkZWxheSI6MC41LCJvcGFjaXR5IjowLCJ4IjotNDAwfV19" data-desktopportrait="1" data-desktoplandscape="1" data-tabletportrait="1" data-tabletlandscape="1" data-mobileportrait="0" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div class="n2-style-988cd5fcc253042be95be1a9c67916a2-heading  n2-ss-img-wrapper n2-ow" style="overflow:hidden;"><img src="//cybercore.vn/wp-content/uploads/2018/07/slide-5-small.png" id="n2-ss-11item29" alt="Image is not available" style="display: inline-block; max-width: 100%; width: auto;height: auto;" class=" n2-ow" title=""></div>
                                                            </div>
                                                            <div class="n2-ss-layer n2-ow n2-ss-has-maxwidth  popmake-1900 container float-right-slide  hover-white pum-trigger" style="margin: 0em; max-width: 1180px; overflow: visible; font-size: 100%; opacity: 0; transform: matrix(1, 0, 0, 1, 293.6, 0); transform-origin: 50% 50% 0px; cursor: pointer;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="1180" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IlJpZ2h0IGZhZGUiLCJkZWxheSI6MSwib3BhY2l0eSI6MCwieCI6LTQwMH1dfQ==" data-desktopportrait="1" data-desktoplandscape="1" data-tabletportrait="1" data-tabletlandscape="1" data-mobileportrait="0" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div class=" n2-ss-img-wrapper n2-ow" style="overflow:hidden;"><img src="https://cybercore.vn/wp-content/uploads/2018/07/btn-dang-ky-phong-game.png" id="n2-ss-11item30" alt="Image is not available" style="display: inline-block; max-width: 100%; width: auto;height: auto;" class=" n2-ow" title=""></div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div data-slide-duration="0" data-id="42" class="n2-ss-slide n2-ss-canvas n2-ow  n2-ss-slide-42" style="width: 1277px; height: 415px; left: -100000px;">
                                            <div data-hash="bdf331ec244fd019b23cd74bc3c698c1" data-desktop="//cybercore.vn/wp-content/uploads/2018/07/6.png" style="" class="n2-ss-slide-background n2-ow" data-opacity="1" data-blur="0" data-mode="fill" data-x="50" data-y="50"><img title="" src="//cybercore.vn/wp-content/uploads/2018/07/6.png" alt="" style="display: none;">
                                                <div class="n2-ss-background-image n2noselftransition" style="opacity: 1; background-position: 50% 50%; background-image: url(&quot;//cybercore.vn/wp-content/uploads/2018/07/6.png&quot;); overflow: hidden; transform-style: flat; backface-visibility: hidden; transform-origin: 50% 50% 0px; transform: matrix(1.12, 0, 0, 1.12, 0, 0); transition: all 10s ease 0s;"></div>
                                            </div>
                                            <div class="n2-ss-layers-container n2-ow" data-csstextalign="center" style="width: 881px; height: 415px; margin-top: 0px; margin-left: 198px;">
                                                <div class="n2-ss-section-outer" style="">
                                                    <div class="n2-ss-layer n2-ow" style="font-size: 16px;" data-csstextalign="inherit" data-desktopportraitmaxwidth="0" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-pm="content" data-desktopportraitpadding="10|*|10|*|10|*|10|*|px+" data-desktopportraitinneralign="inherit" data-type="content" data-rotation="0" data-desktopportrait="1" data-desktoplandscape="1" data-tabletportrait="1" data-tabletlandscape="1" data-mobileportrait="1" data-mobilelandscape="1" data-adaptivefont="1" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                        <div class="n2-ss-section-main-content n2-ss-layer-content n2-ow" style="padding:0.625em 0.625em 0.625em 0.625em ;" data-verticalalign="center">
                                                            <div class="n2-ss-layer n2-ow" style="margin: 0em; overflow: visible; display: none;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="0" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IkZhZGUiLCJvcGFjaXR5IjowfV19" data-desktopportrait="0" data-desktoplandscape="1" data-tabletportrait="0" data-tabletlandscape="1" data-mobileportrait="1" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div id="n2-ss-11item31" class="n2-font-38cd25c499ec1da6f7bd788d93f3c8df-hover n2-style-5db3eb698375544404f3cdafad9da567-heading   n2-ow" style="display:block;">MARKETING HIỆU QUẢ</div>
                                                            </div>
                                                            <div class="n2-ss-layer n2-ow" style="margin: 0em; overflow: visible; display: none;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="0" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IkZhZGUiLCJkZWxheSI6MC41LCJvcGFjaXR5IjowfV19" data-desktopportrait="0" data-desktoplandscape="1" data-tabletportrait="0" data-tabletlandscape="1" data-mobileportrait="1" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div class="n2-ow n2-ow-all n2-ss-desktop n2-ss-mobile n2-ss-tablet">
                                                                    <p class="n2-font-ef00fb91ee234f15b8037cb581776ed5-paragraph  n2-style-534e9b4d532093b74f0acd993e3488e5-heading  n2-ow"><b>CHIẾN LƯỢC TRUYỀN THÔNG CHUYÊN NGHIỆP</b><br>
                                                                        <b>KẾT HỢP VỚI CÁC SỰ KIỆN OFFLINE ĐA DẠNG</b></p>
                                                                </div>
                                                            </div>
                                                            <div class="n2-ss-layer n2-ow n2-ss-has-maxwidth  popmake-1900  hover-white pum-trigger" style="margin: 0em; max-width: 600px; overflow: visible; display: none; cursor: pointer;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="600" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IkZhZGUiLCJkZWxheSI6MSwib3BhY2l0eSI6MH1dfQ==" data-desktopportrait="0" data-desktoplandscape="1" data-tabletportrait="0" data-tabletlandscape="1" data-mobileportrait="1" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div class="nextend-smartslider-button-container n2-ow n2-font-4669165dee3c2406bfe110cc3c6709a8-link " style="cursor: pointer; display:inline-block;white-space:nowrap;"><a style="display:inline-block;" class="n2-style-0c4c15047218596e2dfdd2403e17f29a-heading  n2-ow " onclick="return false;" href="#">ĐĂNG KÝ TƯ VẤN PHÒNG GAME</a></div>
                                                            </div>
                                                            <div class="n2-ss-layer n2-ow n2-ss-has-maxwidth" style="margin: 0em; max-width: 1180px; overflow: visible; font-size: 100%; opacity: 1; transform: matrix(1, 0, 0, 1, 0, 0); transform-origin: 50% 50% 0px;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="1180" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IkRvd25zY2FsZWQiLCJzY2FsZVgiOjAsInNjYWxlWSI6MH1dfQ==" data-desktopportrait="1" data-desktoplandscape="1" data-tabletportrait="1" data-tabletlandscape="1" data-mobileportrait="0" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div class="n2-style-988cd5fcc253042be95be1a9c67916a2-heading  n2-ss-img-wrapper n2-ow" style="overflow:hidden;"><img src="//cybercore.vn/wp-content/uploads/2018/07/slide-6-big.png" id="n2-ss-11item34" alt="Image is not available" style="display: inline-block; max-width: 100%; width: auto;height: auto;" class=" n2-ow" title=""></div>
                                                            </div>
                                                            <div class="n2-ss-layer n2-ow n2-ss-has-maxwidth" style="margin: 0em; max-width: 1180px; overflow: visible; font-size: 100%; opacity: 1; transform: matrix(1, 0, 0, 1, 0, 0); transform-origin: 50% 50% 0px;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="1180" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IkRvd25zY2FsZWQiLCJkZWxheSI6MC41LCJzY2FsZVgiOjAsInNjYWxlWSI6MH1dfQ==" data-desktopportrait="1" data-desktoplandscape="1" data-tabletportrait="1" data-tabletlandscape="1" data-mobileportrait="0" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div class="n2-style-988cd5fcc253042be95be1a9c67916a2-heading  n2-ss-img-wrapper n2-ow" style="overflow:hidden;"><img src="//cybercore.vn/wp-content/uploads/2018/07/slide-6-small.png" id="n2-ss-11item35" alt="Image is not available" style="display: inline-block; max-width: 100%; width: auto;height: auto;" class=" n2-ow" title=""></div>
                                                            </div>
                                                            <div class="n2-ss-layer n2-ow n2-ss-has-maxwidth  popmake-1900  hover-white pum-trigger" style="margin: 0em; max-width: 1180px; overflow: visible; font-size: 100%; opacity: 1; transform: matrix(1, 0, 0, 1, 0, 0); transform-origin: 50% 50% 0px; cursor: pointer;" data-pm="normal" data-desktopportraitmargin="0|*|0|*|0|*|0|*|px+" data-desktopportraitheight="0" data-desktopportraitmaxwidth="1180" data-cssselfalign="inherit" data-desktopportraitselfalign="inherit" data-type="layer" data-rotation="0" data-animations="eyJzcGVjaWFsWmVybyI6MCwidHJhbnNmb3JtT3JpZ2luIjoiNTB8Knw1MHwqfDAiLCJpbiI6W3sibmFtZSI6IkRvd25zY2FsZWQiLCJkZWxheSI6MSwic2NhbGVYIjowLCJzY2FsZVkiOjB9XX0=" data-desktopportrait="1" data-desktoplandscape="1" data-tabletportrait="1" data-tabletlandscape="1" data-mobileportrait="0" data-mobilelandscape="1" data-adaptivefont="0" data-desktopportraitfontsize="100" data-plugin="rendered">
                                                                <div class="n2-style-5db3eb698375544404f3cdafad9da567-heading  n2-ss-img-wrapper n2-ow" style="overflow:hidden;"><img src="https://cybercore.vn/wp-content/uploads/2018/07/btn-dang-ky-phong-game.png" id="n2-ss-11item36" alt="Image is not available" style="display: inline-block; max-width: 100%; width: auto;height: auto;" class=" n2-ow" title=""></div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div data-ssleft="0+15" data-sstop="height/2-previousheight/2" id="n2-ss-11-arrow-previous" class="n2-ss-widget n2-ss-widget-display-desktop n2-ss-widget-display-tablet n2-ss-widget-display-mobile nextend-arrow n2-ib n2-ow nextend-arrow-previous  nextend-arrow-animated-fade" style="position: absolute; width: 32px; height: 32px; top: 191.5px; left: 15px;" role="button" aria-label="Previous slide" tabindex="0"><img class="n2-ow" data-no-lazy="1" data-hack="data-lazy-src" src="data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzIiIGhlaWdodD0iMzIiIHZpZXdCb3g9IjAgMCAzMiAzMiIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTEuNDMzIDE1Ljk5MkwyMi42OSA1LjcxMmMuMzkzLS4zOS4zOTMtMS4wMyAwLTEuNDItLjM5My0uMzktMS4wMy0uMzktMS40MjMgMGwtMTEuOTggMTAuOTRjLS4yMS4yMS0uMy40OS0uMjg1Ljc2LS4wMTUuMjguMDc1LjU2LjI4NC43N2wxMS45OCAxMC45NGMuMzkzLjM5IDEuMDMuMzkgMS40MjQgMCAuMzkzLS40LjM5My0xLjAzIDAtMS40MmwtMTEuMjU3LTEwLjI5IiBmaWxsPSIjZmZmZmZmIiBvcGFjaXR5PSIwLjgiIGZpbGwtcnVsZT0iZXZlbm9kZCIvPjwvc3ZnPg==" alt="Arrow" style="width: 100%;"></div>
                            <div data-ssright="0+15" data-sstop="height/2-nextheight/2" id="n2-ss-11-arrow-next" class="n2-ss-widget n2-ss-widget-display-desktop n2-ss-widget-display-tablet n2-ss-widget-display-mobile nextend-arrow n2-ib n2-ow nextend-arrow-next  nextend-arrow-animated-fade" style="position: absolute; width: 32px; height: 32px; top: 191.5px; right: 15px;" role="button" aria-label="Next slide" tabindex="0"><img class="n2-ow" data-no-lazy="1" data-hack="data-lazy-src" src="data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzIiIGhlaWdodD0iMzIiIHZpZXdCb3g9IjAgMCAzMiAzMiIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTAuNzIyIDQuMjkzYy0uMzk0LS4zOS0xLjAzMi0uMzktMS40MjcgMC0uMzkzLjM5LS4zOTMgMS4wMyAwIDEuNDJsMTEuMjgzIDEwLjI4LTExLjI4MyAxMC4yOWMtLjM5My4zOS0uMzkzIDEuMDIgMCAxLjQyLjM5NS4zOSAxLjAzMy4zOSAxLjQyNyAwbDEyLjAwNy0xMC45NGMuMjEtLjIxLjMtLjQ5LjI4NC0uNzcuMDE0LS4yNy0uMDc2LS41NS0uMjg2LS43NkwxMC43MiA0LjI5M3oiIGZpbGw9IiNmZmZmZmYiIG9wYWNpdHk9IjAuOCIgZmlsbC1ydWxlPSJldmVub2RkIi8+PC9zdmc+" alt="Arrow" style="width: 100%;"></div>
                            <div data-ssleft="width/2-bulletwidth/2" data-ssbottom="0+10" data-offset="10" class="n2-ss-widget n2-ss-widget-display-desktop n2-ss-widget-display-tablet n2-ss-widget-display-mobile nextend-bullet-bar n2-ib n2-ow nextend-bullet-bar-horizontal" style="text-align: center; position: absolute; bottom: 10px; left: 572.5px;">
                                <div class="n2-ow n2-style-1da877f94ec39d33b86fac7462c51834-dot" tabindex="0"></div>
                                <div class="n2-ow n2-style-1da877f94ec39d33b86fac7462c51834-dot" tabindex="0"></div>
                                <div class="n2-ow n2-style-1da877f94ec39d33b86fac7462c51834-dot" tabindex="0"></div>
                                <div class="n2-ow n2-style-1da877f94ec39d33b86fac7462c51834-dot" tabindex="0"></div>
                                <div class="n2-ow n2-style-1da877f94ec39d33b86fac7462c51834-dot n2-active" tabindex="0"></div>
                                <div class="n2-ow n2-style-1da877f94ec39d33b86fac7462c51834-dot" tabindex="0"></div>
                            </div>
                        </div>
                        <div class="n2-clear"></div>
                    </div>
                </div>
                <!-- Nextend Smart Slider 3 #11 - END -->
            </div>
        </div>
    </div>
</div>